{% set version = "20190110-28-ga81397fc4" %}

package:
  name: libdwarf-split
  # add 0.0.0. prefix to conda package versions from previous 'epoch' of version naming based on dates
  version: 0.0.0.{{ version | replace('-', '_') }}

source:
  git_url: https://github.com/davea42/libdwarf-code.git
  git_rev: {{ version }}
  patches:
    - patches/0001-add-enable_libdwarf-and-enable_dwarfdump-to-configur.patch
    - patches/0002-fixup-runtests.sh-scripts-for-conda-env-assumptions.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake       # [win]
    - autoconf    # [unix]
    - automake    # [unix]
    - libtool     # [unix]
    - make        # [unix]
    - pkg-config  # [unix]
    - git  # for better patch application
    - python >=3  # for test scripts
  host:
    - zlib
    - elfutils
  run:

outputs:
  - name: dwarfdump
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - zlib
        - elfutils
        - {{ pin_subpackage('libdwarf', exact=True) }}
      run:
        - {{ pin_subpackage('libdwarf') }}
    files:
      - bin/dwarfdump
      - share/dwarfdump/dwarfdump.conf
      - man/man1/dwarfdump.1
    test:
      requires:
        - zlib
        - {{ pin_subpackage('libdwarf', exact=True) }}
      commands:
        - dwarfdump --version
    about:
      home: https://www.prevanders.net/dwarf.html
      summary: utility dumping DWARF Debugging Information Format to text
      description: |
        The DWARF Debugging Information Format is of interest to programmers working on compilers and
        debuggers (and anyone interested in reading or writing DWARF information). It was developed by a
        committee (known as the PLSIG at the time) starting around 1991. Starting around 1991 SGI got
        involved with the committee and then developed the libdwarf and dwarfdump tools for SGI-internal
        use and as part of SGI IRIX developer tools. From around 1993 dwarfdump and libdwarf were
        shipped (as an executable and archive respectively, not source) with every release of the SGI
        MIPS/IRIX C compiler. In 1994 (I think the correct year) SGI agreed (at my request) to
        open-source libdwarf (and in 1999 to open-source dwarfdump) so anyone could use them.
      #  libdwarf is LGPL-2.1 and dwarfdump is GPL-2.0
      #  There are some files under less-restrictive licenses but there you have it
      license: GPL-2.0-only
      license_family: GPL
      license_file:
        - COPYING
        - dwarfdump/COPYING
        - dwarfdump/DWARFDUMPCOPYRIGHT
        - dwarfdump/GPL.txt
      doc_url: https://www.prevanders.net/libdwarfdoc/
      dev_url: https://github.com/davea42/libdwarf-code
  - name: libdwarf-dev
    build:
      run_exports:
        # he seems to understand semantic versioning https://www.prevanders.net/dwarf.html#nfuture
        # abi lab isn't up to date with latest releases but I emailed libdwarf-list at linuxmail dot org
        # to ask him to request that abilab update to look at GH instead of sourceforge
        - {{ pin_subpackage('libdwarf') }}
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - zlib
        - elfutils
      run:
        - {{ pin_subpackage('libdwarf', exact=True) }}
    files:
      - include/libdwarf.h
      - lib/libdwarf.so          # [linux]
      - lib/libdwarf.dylib       # [osx]
    test:
      requires:
        - zlib
      commands:
        - test -f $PREFIX/include/libdwarf.h
        - test -f $PREFIX/lib/libdwarf${SHLIB_EXT}

    about:
      home: https://www.prevanders.net/dwarf.html
      summary: a library for manipulating DWARF Debugging Information Format (headers & dev stuff)
      description: |
        The DWARF Debugging Information Format is of interest to programmers working on compilers and
        debuggers (and anyone interested in reading or writing DWARF information). It was developed by a
        committee (known as the PLSIG at the time) starting around 1991. Starting around 1991 SGI got
        involved with the committee and then developed the libdwarf and dwarfdump tools for SGI-internal
        use and as part of SGI IRIX developer tools. From around 1993 dwarfdump and libdwarf were
        shipped (as an executable and archive respectively, not source) with every release of the SGI
        MIPS/IRIX C compiler. In 1994 (I think the correct year) SGI agreed (at my request) to
        open-source libdwarf (and in 1999 to open-source dwarfdump) so anyone could use them.
      #  libdwarf is LGPL-2.1 and dwarfdump is GPL-2.0
      #  There are some files under less-restrictive licenses but there you have it
      license: LGPL-2.1-only
      license_family: GPL
      license_file:
        - COPYING
        - libdwarf/LIBDWARFCOPYRIGHT
        - libdwarf/LGPL.txt
        - libdwarf/COPYING
      doc_url: https://www.prevanders.net/libdwarfdoc/
      dev_url: https://github.com/davea42/libdwarf-code
  - name: libdwarf
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - zlib
        - elfutils
        - libzlib
      run:
    files:
      - lib/libdwarf.so.*        # [linux]
      - lib/libdwarf.*.dylib     # [osx]
    test:
      commands:
        - test ! -f $PREFIX/lib/libdwarf*.a
    about:
      home: https://www.prevanders.net/dwarf.html
      summary: a library for manipulating DWARF Debugging Information Format (runtime .so)
      description: |
        The DWARF Debugging Information Format is of interest to programmers working on compilers and
        debuggers (and anyone interested in reading or writing DWARF information). It was developed by a
        committee (known as the PLSIG at the time) starting around 1991. Starting around 1991 SGI got
        involved with the committee and then developed the libdwarf and dwarfdump tools for SGI-internal
        use and as part of SGI IRIX developer tools. From around 1993 dwarfdump and libdwarf were
        shipped (as an executable and archive respectively, not source) with every release of the SGI
        MIPS/IRIX C compiler. In 1994 (I think the correct year) SGI agreed (at my request) to
        open-source libdwarf (and in 1999 to open-source dwarfdump) so anyone could use them.
      #  libdwarf is LGPL-2.1 and dwarfdump is GPL-2.0
      #  There are some files under less-restrictive licenses but there you have it
      license: LGPL-2.1-only
      license_family: GPL
      license_file:
        - COPYING
        - libdwarf/LIBDWARFCOPYRIGHT
        - libdwarf/LGPL.txt
        - libdwarf/COPYING
      doc_url: https://www.prevanders.net/libdwarfdoc/
      dev_url: https://github.com/davea42/libdwarf-code

  - name: libdwarf-testing-meta
    requirements:
      host:
        - zlib
        - elfutils
      run:
        - {{ pin_subpackage('dwarfdump', exact=True) }}
        - {{ pin_subpackage('libdwarf-dev', exact=True) }}
    test:
      requires:
        - {{ compiler('c') }}
        - make         # [unix]
        - autoconf     # [unix]
        - automake     # [unix]
        - libtool      # [unix]
        - python >=3
        - zlib
      source_files:
        - '*'  # yes, we configure to not build and rerun make check with installed artifacts
      commands:
        - dwarfdump --version
        - mkdir build && cd build
          # add -ldwarf to LDLIBS so that linker looks for it in -L$PREFIX/lib provided by our compiler
          # activation scripts
        - LDLIBS+=-ldwarf ../configure --disable-libdwarf --disable-dwarfdump
        - make check
    about:
      home: https://www.prevanders.net/dwarf.html
      summary: library and utility for DWARF (meta with everything enable post-install check)
      description: |
        The DWARF Debugging Information Format is of interest to programmers working on compilers and
        debuggers (and anyone interested in reading or writing DWARF information). It was developed by a
        committee (known as the PLSIG at the time) starting around 1991. Starting around 1991 SGI got
        involved with the committee and then developed the libdwarf and dwarfdump tools for SGI-internal
        use and as part of SGI IRIX developer tools. From around 1993 dwarfdump and libdwarf were
        shipped (as an executable and archive respectively, not source) with every release of the SGI
        MIPS/IRIX C compiler. In 1994 (I think the correct year) SGI agreed (at my request) to
        open-source libdwarf (and in 1999 to open-source dwarfdump) so anyone could use them.

        This package can run 'make check' using installed library and dwarfdump via `conda build --test libdwarf-meta-testing`
      #  libdwarf is LGPL-2.1 and dwarfdump is GPL-2.0
      #  There are some files under less-restrictive licenses but there you have it
      license: LGPL-2.1-only AND GPL-2.0-only
      license_family: GPL
      license_file:
        - COPYING
        - libdwarf/LIBDWARFCOPYRIGHT
        - libdwarf/LGPL.txt
        - libdwarf/COPYING
        - dwarfdump/COPYING
        - dwarfdump/DWARFDUMPCOPYRIGHT
        - dwarfdump/GPL.txt
      doc_url: https://www.prevanders.net/libdwarfdoc/
      dev_url: https://github.com/davea42/libdwarf-code

about:
  home: https://www.prevanders.net/dwarf.html
  summary: library and utility for manipulating DWARF Debugging Information Format
  description: |
    The DWARF Debugging Information Format is of interest to programmers working on compilers and
    debuggers (and anyone interested in reading or writing DWARF information). It was developed by a
    committee (known as the PLSIG at the time) starting around 1991. Starting around 1991 SGI got
    involved with the committee and then developed the libdwarf and dwarfdump tools for SGI-internal
    use and as part of SGI IRIX developer tools. From around 1993 dwarfdump and libdwarf were
    shipped (as an executable and archive respectively, not source) with every release of the SGI
    MIPS/IRIX C compiler. In 1994 (I think the correct year) SGI agreed (at my request) to
    open-source libdwarf (and in 1999 to open-source dwarfdump) so anyone could use them.
  #  libdwarf is LGPL-2.1 and dwarfdump is GPL-2.0
  #  There are some files under less-restrictive licenses but there you have it
  license: LGPL-2.1-only AND GPL-2.0-only
  license_family: GPL
  license_file:
    - COPYING
    - libdwarf/LIBDWARFCOPYRIGHT
    - libdwarf/LGPL.txt
    - libdwarf/COPYING
    - dwarfdump/COPYING
    - dwarfdump/DWARFDUMPCOPYRIGHT
    - dwarfdump/GPL.txt
  doc_url: https://www.prevanders.net/libdwarfdoc/
  dev_url: https://github.com/davea42/libdwarf-code

extra:
  recipe-maintainers:
    - timsnyder
  feedstock-name: libdwarf
